### ISSUE TITLE
Whitespace for cmdlet definitions is ignored

### ISSUE THREAD

**Issue by JoshCrook** [DTW-DanWard/PowerShell-Beautifier#18]
I suppose this is because it's a "comment" but I'll leave it to you to decide if it should be beautified or nto

https://i.imgur.com/yOEXvHa.png

**Comment by DTW-DanWard** [comment]
Hmmmm that's a new case I haven't seen.  Typically the help text is put before the function keyword.  I didn't think Get-Help would correctly read help comment text when inside the function but it does in fact work.  Interesting.

The parser sees that text all as one block (see image) which is why only the first line is getting indented.  The cleanest fix would probably be to not indent the line if it's Type = Comment and SYNOPSIS is detected in the comment.  Does that work for you?

I'm not sure if programmatically breaking up that multi-line comment and indenting each line would be a good idea.
![image](https://user-images.githubusercontent.com/2632539/28951426-e81f6264-7898-11e7-8b99-9f9a96e57596.png)

**Comment by JoshCrook** [comment]
That does work.

Though, I can always start putting the help text out of the function if that's best practice. I believe this is the way I saw it the first time and just have always done it.

**Comment by DTW-DanWard** [comment]
I've been looking around and have seen mixed use, so neither way is the official standard.  I'll make the change tonight.

**Comment by DTW-DanWard** [comment]
Hey @JoshCrook - change is made; give it a try.
